version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: welcomp_apps
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - 'db_data:/var/lib/mysql'

  pma:
    image: phpmyadmin/phpmyadmin:5.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8080:80'

volumes:
  db_data: